name: 'Publish'

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@v3

      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Run Tests'
        run: npm run test --if-present

      - name: 'Publish Package'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
